# Generated by Django 5.2.5 on 2025-09-05 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SynchronizationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата синхронизации",
                    ),
                ),
                (
                    "new_events_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество новых ивентов"
                    ),
                ),
                (
                    "updated_events_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество обновленных ивентов"
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат синхронизации",
                "verbose_name_plural": "Результаты синхронизации",
            },
        ),
    ]
