# Generated by Django 5.2.5 on 2025-09-05 16:03

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import events.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Platform Name"),
                ),
            ],
            options={
                "verbose_name": "Platform",
                "verbose_name_plural": "Platforms",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Event Title")),
                (
                    "date_of_event",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Event Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "OPEN"), ("CLOSED", "CLOSED")],
                        default=events.models.EventStatus["OPEN"],
                        max_length=10,
                        verbose_name="Event Status",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Event Updated"
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="events.platform",
                        verbose_name="Event Platform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-date_of_event"],
            },
        ),
    ]
